### ISSUE TITLE
How to rename the file for storage?

### ISSUE THREAD

**Issue by hassansaqib** [DevFactoryCH/media#11]
Hi, I am looking to rename the uploaded file. Can you guide me how can I do it?

**Comment by markcameron** [comment]
Not sure you can rename the file once you send it to `saveMedia()`, I think your best bet would be to rename the file before you send it to `saveMedia()`.

```
$uploaded_file = Input::file('file');
$renamed_file = $uploaded_file->rename(DIRECTORY, NEW_NAME);
$model->saveMedia($renamed_file);
```

That replacing `DIRECTORY` and `NEW_NAME` with a tmp folder and new name should let you rename it before saving.
