### ISSUE TITLE
Bugs in file models/Media

### ISSUE THREAD

**Issue by alexglue** [DevFactoryCH/media#5]
this is what u need:

```
  public function getUrlAttribute() {
    return Illuminate\Support\Facades\URL::asset(\Config::get('media.config.files_directory') . $this->filename);
  }
```

and this is what u got:

```
  public function getUrlAttribute() {
    return \Url::asset(\Config::get('media::files_directory') . $this->filename);
  }
```

I do not have \Url class, and u do not publish config with name "media" but with name "media.config"

*I use lara 5.1

_Temp Solution for those who got this bug to:_
1) class YourModelMedia extends Devfactory\Media\Models\Media
2) put following method in it:

```
    public function getUrlAttribute() {
        return Illuminate\Support\Facades\URL::asset(Illuminate\Support\Facades\Config::get('media.config.files_directory') . $this->filename);
    }
```

3) add method media() to model using trait MediaTrait:

```
    public function media() {
        return $this->morphMany(YourModelMedia::class, 'mediable');
    }
```

**Comment by markcameron** [comment]
Hi, thanks for noticing this. Leftovers from migrating from laravel 4. I'll add the missing namespace.

**Comment by markcameron** [comment]
Tagged a new release `2.0.4` with this change. Let me know if this works better for you. I don't have any laravel 5 projects using this package to test it with.

Thanks
