### ISSUE TITLE
Composer throws warning: Ambiguous class resolution.

### ISSUE THREAD

**Issue by wunc** [DevFactoryCH/media#8]
When running `composer update`, the latest version of Composer now throws a warning:

```
Warning: Ambiguous class resolution, "CreateMediaTable" was found in both "$baseDir . '/database/migrations/2014_11_11_110645_create_media_table.php" and "/var/www/oar/vendor/devfactory/media/src/migrations/2014_11_11_110645_create_media_table.php", the first will be used.
Warning: Ambiguous class resolution, "UpdateNameAltTitleInMediaTable" was found in both "$baseDir . '/database/migrations/2015_03_26_135428_update_name_alt_title_in_media_table.php" and "/var/www/oar/vendor/devfactory/media/src/migrations/2015_03_26_135428_update_name_alt_title_in_media_table.php", the first will be used.
```

**Comment by markcameron** [comment]
Hi,

Yeah, I need to look into that. Made this package before Laravel 5.0 was finalized, and I think you no longer need to publish the migrations when they are in a package, hence why now it gives the double file warning

**Comment by wunc** [comment]
This might be too roundabout, but the way that Entrust publishes migrations is with a migration generator artisan command that uses blade to insert variables into the migration file: 
https://github.com/Zizaco/entrust/blob/laravel-5/src/Entrust/EntrustServiceProvider.php
https://github.com/Zizaco/entrust/blob/laravel-5/src/commands/MigrationCommand.php
https://github.com/Zizaco/entrust/blob/laravel-5/src/views/generators/migration.blade.php

**Comment by sirsquall** [comment]
It's fixed in the new release
